server:
  port: 20001
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ruoyi.payment.api.entity
logging:
  level:
    com.ruoyi.payment.mapper: debug
spring:
  application:
    name: payment-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.198.129:8848
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_advanced?useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always